services:
  backend:
    build: ./backend/.
    ports:
      - "4000:5000"
  frontend:
    build: ./frontend/.
    ports:
      - "8000:3000"
    environment:
      - REACT_APP_BACKEND_ENDPOINT=http://127.0.0.1:4000/