name: newomania
services:
  backend:
    build: ./backend/.
    ports:
      - "4000:5000"
  frontend:
    build: ./frontend/.
    ports:
      - "80:3000"
    environment:
      - REACT_APP_BACKEND_ENDPOINT=http://3444:4000/